from cms import views
from django.urls import path, re_path
from django.views.decorators.cache import cache_page

urlpatterns = [
    path("", views.index, name="index"),
    # path("serenity/", views.serenity, name="serenity"),
    re_path(r'^serenity/?$', views.serenity, name="serenity"),
    # path("laundry/", views.laundry, name="laundry"),
    # path("harrow/", views.harrow, name="harrow"),
    re_path(r'^harrow/?$', views.harrow, name="harrow"),
    # path("oxley/", views.oxley, name="oxley"),
    re_path(r'^oxley/?$', views.oxley, name="oxley"),
    # path("francisco/", views.francisco, name="francisco"),
    re_path(r'^francisco/?$', views.francisco, name="francisco"),
    # path("porscha/", views.porscha, name="porscha"),
    re_path(r'^porscha/?$', views.porscha, name="porscha"),
    # path("projects/", views.project, name="projects"),
    re_path(r'^projects/?$', views.project, name="projects"),
    # path("projects/<slug:slug>/", views.project_details, name="project-details"),
    re_path(r'^projects/(?P<slug>[\w-]+)/?$', views.project_details, name="project-details"),
    # path("bathroom-planner/", views.bathroom_planner, name="bathroom-planner"),
    re_path(r'^bathroom-planner/?$', views.bathroom_planner, name="bathroom-planner"),
    # path("laundry-planner/", views.laundry_planner, name="laundry-planner"),
    re_path(r'^laundry-planner/?$', views.laundry_planner, name="laundry-planner"),
    # path("video/", views.video, name="video"),
    re_path(r'^video/?$', views.video, name="video"),
    # path("subscribe/", views.subscribe, name="subscribe"),
    re_path(r'^subscribe/?$', views.subscribe, name="subscribe"),
    # path("catalogues/", views.catalogues, name="catalogues"),
    re_path(r'^catalogues/?$', views.catalogues, name="catalogues"),
    # path("terms-of-trade/", views.terms_of_trade, name="terms-of-trade"),
    re_path(r'^terms-of-trade/?$', views.terms_of_trade, name="terms-of-trade"),
    # path("return-policy/", views.return_policy, name="return-policy"),
    re_path(r'^return-policy/?$', views.return_policy, name="return-policy"),
    # path("about-us/", views.about_us, name="about-us"),
    re_path(r'^about-us/?$', views.about_us, name="about-us"),
    # path("concept-showroom/", views.concept_showroom, name="concept-showroom"),
    re_path(r'^concept-showroom/?$', views.concept_showroom, name="concept-showroom"),
    # path("contact-us/", views.contact, name="contact"),
    re_path(r'^contact-us/?$', views.contact, name="contact"),
    re_path(r'^universalplumbing/?$', views.universal, name="universalplumbing"),
    # path("site-map/",views.site_map,name="site-map"),
    re_path(r'^site-map/?$',views.site_map,name="site-map"),
    # path("site_verify/",views.site_verify,name="site_verify"),
    re_path(r'^site_verify/?$',views.site_verify,name="site_verify"),
    # path("site-map/categories/",views.site_map_category,name="site-map-categories"),
    re_path(r'^site-map/categories/?$',views.site_map_category,name="site-map-categories"),
    # path("vista-range/",views.vista_range,name="vista-range"),
    re_path(r'^vista-range/?$', views.vista_range, name="vista-range"),
    #path("404",views.not_found_404,name="not-found-404")
]
