FROM python:3.10.7

RUN python3 --version
RUN pip --version

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
RUN mkdir /alsco_service_web
WORKDIR /alsco_service_web
COPY ./back-end /alsco_service_web/
RUN pip install -r requirements.txt
RUN pip install -r requirements/base.txt

RUN mkdir /alsco_service_frontend
WORKDIR /alsco_service_frontend
COPY ./front-end /alsco_service_frontend/
#RUN rm /usr/local/bin/yarn
#RUN rm /usr/local/bin/yarnpkg
RUN curl -sL https://deb.nodesource.com/setup_14.x | bash -
RUN apt-get install -y nodejs
RUN node -v
RUN npm -v
RUN npm install -g yarn
RUN yarn install
RUN yarn build

WORKDIR /alsco_service_web