# Generated by Django 4.2 on 2023-04-27 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='resource_url',
            field=models.FileField(blank=True, null=True, upload_to='assets/product_resource/'),
        ),
    ]
