# Generated by Django 4.2 on 2023-05-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_resource_resource_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='meta_title',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
