# Generated by Django 4.2 on 2023-05-09 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_option_dimension_product_dimension'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='cart_item',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='products.cartitem'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='long_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
