# Generated by Django 4.2 on 2023-05-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_orderitem_cart_item_orderitem_long_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoption',
            name='option_type',
            field=models.CharField(choices=[('COLOUR', 'Colour'), ('SIZE', 'Size'), ('SLAB_TOP', 'Slab Top'), ('BASIN', 'Basin'), ('EXTRUSION', 'Extrusion'), ('TAP_HOLE', 'Tap Hole'), ('COSMETIC_DRAWER', 'Cosmetic Drawer'), ('HANDLES', 'Handles'), ('DEMISTER', 'Demister'), ('OTHER', 'Other')], max_length=25),
        ),
    ]
