# Generated by Django 4.2 on 2023-05-10 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productoption_display_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storelocation',
            name='customer_emails',
        ),
        migrations.CreateModel(
            name='StoreLocationEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('store_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_emails', to='products.storelocation')),
            ],
            options={
                'verbose_name': 'Customer Email Address',
                'verbose_name_plural': 'Customer Email Addresses',
            },
        ),
    ]
