# Generated by Django 4.2 on 2023-05-10 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_storelocation_customer_emails_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product_sku',
            field=models.CharField(max_length=100),
        ),
    ]
