# Generated by Django 4.2 on 2023-06-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_description_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='storelocation',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='storelocation',
            name='can_appear_checkout',
            field=models.BooleanField(default=False),
        ),
    ]
