# Generated by Django 4.2 on 2023-06-05 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_storelocation_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='label',
        ),
    ]
