# Generated by Django 4.2 on 2023-06-07 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_option_label'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storelocation',
            options={'ordering': ['name']},
        ),
    ]
