# Generated by Django 4.2 on 2023-06-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_product_code_alter_product_description_short_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryproduct',
            name='hide_thumbnail',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='galleryproduct',
            name='sku_matching',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productoption',
            name='include_gallery',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product_sku_option',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
