# Generated by Django 4.2 on 2023-06-27 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_galleryproduct_hide_thumbnail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupProduct',
            fields=[
                ('uuid', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='productoption',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.CreateModel(
            name='ProductOptionDependRel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('unavailable', models.BooleanField(default=False)),
                ('depend_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.option')),
                ('depend_productoption', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depend_productoption_all', to='products.productoption')),
                ('productoption', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productoption')),
            ],
            options={
                'ordering': ['sequence'],
                'unique_together': {('productoption', 'depend_productoption', 'depend_option')},
            },
        ),
        migrations.CreateModel(
            name='OptionDependRel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('unavailable', models.BooleanField(default=False)),
                ('depend_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='depend_option', to='products.option')),
                ('depend_productoption', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depend_productoption_option', to='products.productoption')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.option')),
            ],
            options={
                'ordering': ['sequence'],
                'unique_together': {('option', 'depend_option', 'depend_productoption')},
            },
        ),
        migrations.CreateModel(
            name='GroupProductRel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('group_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.groupproduct')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'ordering': ['sequence'],
                'unique_together': {('product', 'group_product')},
            },
        ),
        migrations.AddField(
            model_name='groupproduct',
            name='products',
            field=models.ManyToManyField(through='products.GroupProductRel', to='products.product'),
        ),
        migrations.AddField(
            model_name='option',
            name='option_dependencies',
            field=models.ManyToManyField(related_name='depend_options_all', through='products.OptionDependRel', to='products.option'),
        ),
        migrations.AddField(
            model_name='product',
            name='groups',
            field=models.ManyToManyField(related_name='groups_all', through='products.GroupProductRel', to='products.groupproduct'),
        ),
        migrations.AddField(
            model_name='productoption',
            name='product_option_dependencies',
            field=models.ManyToManyField(related_name='depend_product_options_all', through='products.ProductOptionDependRel', to='products.productoption'),
        ),
    ]
