# Generated by Django 4.2 on 2023-07-19 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_alter_contact_email_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Universal',
            fields=[
                ('uuid', models.CharField(default='', max_length=36, primary_key=True, serialize=False)),
                ('towel_rail', models.CharField(blank=True, choices=[('', 'Select towel rail type'), ('ST65', 'ST65'), ('ST75', 'ST75'), ('ST78', 'ST78'), ('SL125', 'SL125'), ('SL115', 'SL115'), ('C100', 'C100'), ('SL130', 'SL130')], max_length=50)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('company_name', models.CharField(blank=True, max_length=100)),
                ('shipping_address', models.CharField(blank=True, max_length=255)),
                ('email_address', models.EmailField(max_length=255)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('proof_purchase', models.FileField(blank=True, upload_to='proof_purchase')),
            ],
            options={
                'ordering': ['-create_date'],
            },
        ),
    ]
