# Generated by Django 4.2 on 2023-04-26 23:06

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('type_laundry', models.CharField(blank=True, max_length=255)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=255)),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=150)),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('published', models.BooleanField(default=True)),
                ('image', models.FileField(blank=True, upload_to='images/project/')),
                ('image_banner', models.FileField(blank=True, upload_to='images/project/banner/')),
            ],
            options={
                'ordering': ['-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, upload_to='images/project/post/')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='additional_images', to='blog.blogpost')),
            ],
        ),
    ]
