# Generated by Django 4.2 on 2023-07-26 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_addresses_is_default_customuser_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addresses',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
